### PR TITLE
Add Italian language into app config 🤌

### PR DESCRIPTION
**Pull request by giacomofuria**
Hi, after uploading the Italian translations on Crowdin I added the Italian language code in app.config and removed the & character on some labels that were not being translated. 

I have two questions:

1. What is the purpose of the & character before a label ? 

2. Can this removal cause any problems ?

Thanks !

### CODE REVIEW

**Review by jlipps — COMMENTED** [review]
yes, we need the `&` symbol since that is how on windows and linux the OS knows what the keyboard shortcut should be. so with `&Reload` the keyboard shortcut for that menu item will be `R`.

**Comment by giacomofuria** [comment]
Hi @jlipps , I tried to handle the '&' out of the translation function so that we can have keys to translate without the '&' character. This also keeps the keyboard shortcuts on Windows and linux working.

Can this solution be ok ?

**Review by jlipps — APPROVED** [review]
yeah, i think this makes sense. and just to be sure, did you test a build with these changes to make sure it works?

**Comment by giacomofuria** [comment]
yeah, I tested it on my pc with windows 11

**Review by jlipps — APPROVED** [review]

**Pull request merged**
